name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=2.7
  - samtools
  - bedtools
  - pysam
  - pblat
  - htslib
  - numpy
  - scipy
  - matplotlib
  - logzero
  - statsmodels
  - awscli
  - pip

    